config/routes.rb
Rails.application.routes.draw do
  devise_for :super_admins, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :admin
  devise_for :student

  mount ActionCable.server => '/cable'

  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == 'kapil' && password == 'kapil@7588584810'
  end
  mount Sidekiq::Web => '/sidekiq'

  post 'sync-attendance', to: 'admin/api/attendance#create'
  get  'machines', to: 'admin/api/attendance#machines'
  # mount PgHero::Engine, at: "/pg-stats-k"

  # authenticate :admin, -> (admin) { admin.present? } do
  #   mount PgHero::Engine, at: "pghero"
  # end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'students/home#index'

  get  'pay/:slug', to: 'pay#show'
  post 'pay', to: 'pay#create', as: :pay_path
  post 'process-pay', to: 'pay#process_pay', as: :pay_process_path
  post 'auth-pay', to: 'pay#auth_pay', as: :pay_auth_path

  post 'process-gform', to: 'students/google_forms#register'

  get 'new-admission', to: 'students/admissions#show'
  get 'registration', to: 'students/admissions#registration_form'
  post 'register', to: 'students/admissions#register'
  get 'registration-confirmation', to: 'students/admissions#registration_confirmation'
  get 'foundation-admission', to: 'students/admissions#foundation_show'
  get 'admission-done', to: 'students/admissions#admission_done'
  post 'admission-done', to: 'students/admissions#admission_done'
  post 'ADMISSION-DONE', to: 'students/admissions#admission_done'
  get 'ADMISSION-DONE', to: 'students/admissions#admission_done'
  get 'admission-done-set/:id', to: 'students/admissions#admission_done_set', as: :rcc_set_path

  # added for razorpay
  get 'initiate_pay', to: 'students/payments#initiate_pay', as: :initiate_pay
  post 'process-admission', to: 'students/payments#process_payment'
  post 'authorize_payment', to: 'students/payments#authorize_payment'
  get  'process-admission', to: 'students/payments#process_payment'
  get  'confirm_payment', to: 'students/payments#confirm_payment'

  get 'print-receipt/:reference_id', to: 'students/admissions#print_receipt'

  get 'pay-installment', to: 'students/admissions#pay_installment'
  get 'pay-due-fees', to: 'students/admissions#pay_due_fees'
  get 'pay_due_fees', to: 'students/admissions#pay_due_fees'

  namespace :students do
    get 'videos' => 'videos#lectures'
    get 'lectures' => 'videos#lectures'
    get 'lectures/:video_id' => 'videos#show_lecture'
    get 'lectures_tp/:tp_streams_id' => 'videos#show_lecture_tp'
    get 'category_videos/:id' => 'videos#category_videos'
    get 'yt-player' => 'videos#play_yt'
    get 'play-yt-video' => 'videos#play_yt_video'
    get 'otp_input', to: 'login#otp_input'
    post 'process_otp', to: 'login#process_otp'

    post 'authorise', to: 'login#authorise'
    get "auto-auth", to: 'home#auto_auth'
    root to: 'home#index'
    get :tests, to: 'home#tests', as: :tests
    get :progress_report, to: 'home#progress_report', as: :progress_report
    get :instructions, to: 'home#instructions', as: :exam_instructions
    get :confirmation, to: 'home#confirmation', as: :exam_confirmation
    get :question_bank, to: 'home#question_bank', as: :question_bank
    get :subscription, to: 'home#subscription', as: :exam_subscription
    get "summary/:exam_id", to: 'home#summary', as: :exam_summary
    # get :exam_data, to: 'home#exam_data'
    get :exam_data, to: 'exams#exam_data'
    get :exam_data_s3, to: 'exams#exam_data_s3'
    get :is_exam_valid, to: 'exams#is_exam_valid'
    get :print_hall_ticket, to: 'exams#print_hall_ticket'
    get "exam/:id", to: 'home#exam'
    put "sync/:exam_id/", to: 'home#sync'
    put "submit/:exam_id/", to: 'home#submit'
    resources :mock_tests
    get 'home/profile', to: 'home#profile'
    patch 'home/update_profile', to: 'home#update_profile'

    resources :model_answers
    resources :admissions do
      post :create_installment, on: :collection
    end
    resources :study_pdfs
    resources :notifications
    resources :progress_cards
    resources :messages
    resources :live_classes
  end


  # routes of admin panel
  namespace :admin do
    root to: 'dashboard#show'
    resource :dashboard
    resources :reports do
      get :exam_detailed_report
      get :generate_progress_report
    end
    resources :exams do
      collection do
        get 'question_bank', to: 'exams#question_bank'
        get 'new_jee', to: 'exams#new_jee'
        post 'change_question_answer'
        post :create_section
      end
      get :re_evaluate_exam
    end
    resources :practice_questions
    resources :students do
      root to: 'students#index'
      get   :import, on: :collection
      post  :process_import, on: :collection
      post  :process_import_fees_due, on: :collection
      get   :reset_login
      get   :disable
      get   :enable
      get   :progress_report
      get   :attendance_report
      post  :attendance_report
      post  :attendance_report_pdf
    end
    resources :batches do
      root to: 'batches#index'
      get   :disable
      get   :change_batches, on: :collection
      post  :process_change_batches, on: :collection
      get   :downoload_cet
    end
    resources :batch_groups

    get 'dashboard/profile', to: 'dashboard#profile'
    patch 'dashboard/update_profile', to: 'dashboard#update_profile'

    resources :video_lectures do
      get :chats
      get :student_video_views
      get :modity_student_views
    end
    resources :android_apps
    resources :users do
      get :profile, on: :collection
    end
    resources :study_pdfs
    resources :notifications
    resources :genres do
      get :hide
      get :show
      put :student_folder_access
    end
    resources :study_pdf_types
    resources :messages
    resources :zoom_meetings do
      get :chats
    end
    resources :subjects
    resources :omr
    resources :attendance do
      get :overview_report, on: :collection
      get :settings, on: :collection
      get :sms_logs, on: :collection
      post :change_auto_sms_settings, on: :collection
      post :send_batch_sms, on: :collection
      get :download_xls_report, on: :collection
      collection do
        resources :holidays
      end
    end

    resources :micro_payments
    resources :banners
    resources :att_machines do
      patch :enable
      patch :disable
    end

    resources :id_cards, only: [:index] do
      post :upload_photos, on: :collection
      get :print_cards, on: :collection
      post :print_cards, on: :collection
      post :generate_prints, on: :collection
    end

    namespace :api do
      resources :students
      resources :attendance
      resources :demo_logins

      # new admin api's for admin react front end.
      namespace :v2 do
        get 'get-token', to: 'auth#get_token'
        post 'login', to: 'auth#login'
        get 'fees-details', to: 'fees#details'
        get 'payment-history', to: 'fees#payment_history'
        post 'fees-transaction', to: 'fees#create_fees_transaction'
        get  'reports/collection', to: 'fees_reports#collection'
        get  'reports/collection_csv', to: 'fees_reports#collection_csv'
        get  'reports/due_fees', to: 'fees_reports#due_fees'
        get  'reports/due_fees_csv', to: 'fees_reports#due_fees_csv'
        get  'reports/notes', to: 'fees_reports#notes'
        get  'reports/print_status', to: 'fees_reports#print_status'
        post 'reports/set_print_status', to: 'fees_reports#set_print_status'
        get  'reports/pending-fees', to: 'fees_reports#pending_fees'
        get  'batches', to: 'batches#index'
        resources :students do
          get   :pending_amount, on: :collection
          get   :issued_notes
          post  :issue_notes
          post  :apply_discount
          get   :suggested_roll_number, on: :collection
          post  :change_course

          collection do
            resources :discounts, only: [:index, :create] do
              post :remove_discount, on: :collection
            end
          end
        end
        resources :notes
      end
    end
  end

  get 'current-server-time', to: 'home#current_server_time'

  namespace :api do
    namespace :v1 do
      post 'sign-in', to: 'students#login'
      post 'update-fcm-token', to: 'students#update_fcm_token'
      get  'is-form-registered', to: 'students#is_form_registered'
      get 'dashboard_data', to: 'home#dashboard_data'
      get 'gallery', to: 'home#gallery'
      get 'app-version', to: 'home#app_version'
      get 'categories', to: 'videos#categories'
      get 'categories/:id/videos', to: 'videos#category_videos'

      resources :notifications, only: [:index]
      resources :videos, only: [:index] do
        get   :get_yt_url
        post  :set_yt_url
        get   :need_url
        get   :get_ytdlp_url
        get   :get_ytdlp_url_from_youtube
      end
      resources :study_pdfs, only: [:index]
      resources :meetings, only: [:index]
      resources :trackers
    end

    # NEW ROUTES
    namespace :v2 do
      resources :students, only: [:index] do
        post 'login', on: :collection
        get  :progress_report, on: :collection
        post :register, on: :collection
        get  :de_active, on: :collection
      end
      resources :notifications
      resources :exams
      get 'subjects', to: 'subjects#index'
      get 'subjects/:id/folders', to: 'subjects#subject_folders'
      get 'subjects/:subject_id/folders/:folder_id/pdfs', to: 'subjects#folder_pdfs'
      get 'subjects/:subject_id/folders/:folder_id/videos', to: 'subjects#folder_videos'
      resources :videos, only: [] do
        post :like
        post :dislike

        get :comments
        post :add_comment
        post :remove_comment
        get :tp_streams_details
      end
    end
  end
end

app/controllers/admin/api/students_controller.rb
class Admin::Api::StudentsController < Admin::Api::ApiController
  def index
    students = Student.where(org: current_org).where.not(rfid_card_number: [nil, ""]).includes(:batches).map do |student|
      {
        id: student.id,
        name: student.name,
        roll_number: student.roll_number,
        batches: student.batches.pluck(:name).join(', '),
        parent_mobile: student.parent_mobile,
        rfid_card_number: student.rfid_card_number
      }
    end
    render json: students, status: :ok
  end
end

app/controllers/admin/api/v2/students_controller.rb
class Admin::Api::V2::StudentsController < Admin::Api::V2::ApiController

  def index
    if params[:type] == 'online' && params[:roll_number].present?
      # new_admission = NewAdmission.find_by(id: params[:ref_number])
      # if new_admission.present?
      #   student_id = new_admission.student_id
      #   @students = Student.where(id: student_id)
      # end
      if current_admin.roles.include?('online_pay')
        @students = Student.where(org_id: current_org.id, roll_number: params[:roll_number])
      else
        @students = []
      end
    else
      if params[:qr_code].present?
        student_id = params[:qr_code].split("|")[1]
        @students = Student.where(id: student_id)
      elsif params[:roll_number].present? && params[:parent_mobile].present?
        @students = Student.where(org_id: current_org.id, roll_number: params[:roll_number], parent_mobile: params[:parent_mobile])
      elsif params[:roll_number].present?
        @students = Student.where(org_id: current_org.id, roll_number: params[:roll_number])
      elsif params[:parent_mobile].present?
        @students = Student.where(org_id: current_org.id, parent_mobile: params[:parent_mobile])
      end

      if @students.present?
        batch_ids = Batch.where(org_id: current_org.id).joins(:batch_fees_templates).ids.uniq
        # filtering batches of the current admin only.
        batch_ids = current_admin.batches.ids & batch_ids
        if params[:is_new] == 'true'
          @students = @students.includes(:batches).where(batches: { id: batch_ids })
        else
          @students = @students.joins(:fees_transactions).includes(:batches).where(batches: { id: batch_ids })
        end
      end
    end
  end

  def suggested_roll_number
    roll_number = (params[:orgCode] == '102' ? Student.random_roll_number(5) : Student.random_roll_number)

    render json: { roll_number: roll_number }
  end

  def create
    system_roll_number = params[:roll_number] || Student.random_roll_number
    errors = []

    # errors << "Invalid permissions" unless current_admin.roles.include?('payments')

    errors << "In-valid batch" if params[:batch_id].blank?

    if params[:parentMobile].to_s.length != 10 || params[:studentMobile].to_s.length != 10
      errors << "In-valid student or parent mobile"
    end

    errors << "In-valid batch" if params[:batch_id].blank?
    batch = Batch.find(params[:batch_id])
    errors << "In-valid batch" if batch.blank?

    render json: errors, status: :unprocessable_entity and return if errors.present?

    create_student_params = student_params.merge({
      org_id: current_org.id,
      gender: params[:gender] == 'male' ? 0 : 1,
      email: "#{system_roll_number}@#{current_org.subdomain}.eduaakar.com",
      roll_number: system_roll_number,
      password: student_params[:parent_mobile],
      raw_password: student_params[:parent_mobile],
      data: { discount_id: params[:discountId]}
    })

    student = Student.create(create_student_params)

    if student.errors.present?
      render json: student.errors.full_messages, status: :unprocessable_entity and return
    end

    student.batches << batch
    if current_org.rcc? && params[:rcc_batch].present? && params[:rcc_batch] != '-'
      student.data[:rcc_batch] = params[:rcc_batch]
      student.save

      batch_name = batch.name
      batch_name = "11th-LTR-PCB-2023-24" if batch.id == 857
      second_batch = Batch.find_by(org_id: current_org.id, name: "#{batch_name} [#{params[:rcc_batch]}]")
      student.batches << second_batch if second_batch
    end

    render json: student
  end

  # need to add a filter to show, students associated with the current admin.
  def pending_amount
    if params[:qr_code].present?
      student_id = params[:qr_code].split("|")[1]
      @student = Student.find_by(id: student_id)
    else
      batch_ids = current_admin.batches.ids
      if params[:roll_number].present? & params[:parent_mobile].present?
        @students = Student.where(org_id: current_org.id).includes(:batches).where(batches: { id: batch_ids }).where(roll_number: params[:roll_number], parent_mobile: params[:parent_mobile])
      elsif params[:roll_number].present?
        @students = Student.where(org_id: current_org.id).includes(:batches).where(batches: { id: batch_ids }).where(roll_number: params[:roll_number])
      elsif params[:parent_mobile].present?
        @students = Student.where(org_id: current_org.id).includes(:batches).where(batches: { id: batch_ids }).where(parent_mobile: params[:parent_mobile])
      end
      @student = @students.first
    end

    render json: { message: "student not found" }, status: :unprocessable_entity and return if @student.blank?

    @pending_amount = FeesTransaction.student_pending_fees(@student.id)
    @paid_percent = FeesTransaction.student_paid_percent(@student.id, @pending_amount) rescue 0
    if @pending_amount >= 4_00_000
      @message = "No Template assigned to student batch"
    end
  end

  def issued_notes
    @student_notes = StudentNote.where(student_id: params[:student_id]).includes(:note)
  end

  def issue_notes
    if params[:student_id].present? && params[:note_id].present?
      student_note = StudentNote.create(
        org_id: current_org.id,
        student_id: params[:student_id],
        note_id: params[:note_id],
        comment: params[:comment],
      )

      render json: student_note and return
    end

    render json: {message: "Can not create student notes"}, status: :unprocessable_entity
  end

  def change_course
    # unless current_admin.roles.include?('change_course')
    #   render json: {message: "Can not change course"}, status: :unprocessable_entity
    # end

    student = Student.find_by(org_id: current_org.id, id: params[:student_id])
    batch = Batch.find_by(id: params[:new_batch_id])

    if student && batch
      CourseChangeEntry.create({
        student: student,
        old_batch_id: student.batches.joins(:batch_fees_templates).ids.uniq.first,
        new_batch_id: batch.id,
        pending_amount: FeesTransaction.student_pending_fees(student.id),
        fees_paid_data: student.fees_transactions&.as_json
      })
      student.batches.destroy_all
      student.batches << batch

      # soft deleting fees tranactions with paranoid gem, so that we can refer them.
      student.fees_transactions.destroy_all

      render json: {message: "successful."}
    else
      render json: {message: "Can not change course"}, status: :unprocessable_entity
    end
  end

  def apply_discount
    student = Student.find_by(org_id: current_org.id, id: params[:student_id])

    if student
      student.data[:discount_id] = params[:discount_id]
      student.save
      render json: {} and return
    end

    render json: {message: "Cannot apply discount"}, status: unprocessable_entity
  end

  private

  def student_params
    {
      name: params[:name],
      mother_name: params[:mother_name],
      date_of_birth: params[:date_of_birth],
      ssc_marks: params[:ssc_marks],
      address: params[:address],
      student_mobile: params[:studentMobile],
      parent_mobile: params[:parentMobile],
      category: params[:category]
    }
  end
end
  

app/controllers/admin/api/v3/students_controller.rb
class Admin::Api::V3::StudentsController < Admin::Api::V2::ApiController

  def index
    render json: { students: Student.first(20) }
  end

  private
end

app/views/students/live_classes/index.html.erb
<% @live_classes.each_slice(2) do |live_classes_slice| %>
  <div class="row">
    <% live_classes_slice.each do |live_class| %>
      <div class="col-sm-6 col-sx-12">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title"><%= live_class[:subject] %></h5>
            <p class="card-text"><%= live_class[:teacher_name] %></p>
            <p class="card-text"><%= live_class[:datetime_of_meeting].strftime("%d-%B-%Y %I:%M%p") %></p>
              <% if live_class.vimeo? %>
                <a href="<%= students_live_class_path(live_class) %>" class="btn btn-primary">
                  Join Live Class
                </a>
              <% else %>
                <a href="<%= live_class.zoom_meeting_url %>" class="btn btn-primary">
                  Join Live Class
                </a>
              <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/students/live_classes/show.html.erb
<div class="col-md-8">
  <h5>Your Live class </h5>
  <div style="padding:56.25% 0 0 0;position:relative;">
      <iframe src="<%= @video_url %>" frameborder="0" allow="autoplay; fullscreen" allowfullscreen style="position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div>
  </div>
  <div class="col-md-4">
  <h4>live Chat Messages</h4>
  <div class="msg-container">
    <% @messages.each do |message| %>
      <div class="<%= message.sender_type == 'Student' ? 'student-msg' : 'admin-msg' %>">
        <p>
        <b>[<%= message.sender_id%>] <%= message.sender_name%>:</b>
        <%= message.message %>
        </p>
        <span class="time-right">
        <%= message.created_at.strftime("%I:%M %p") %>
        </span>
      </div>
    <% end %>
  </div>

  <div class="input-group">
    <input id="chatMessage" type="text" class="form-control" placeholder="Enter your message..." data-name="<%= @student.name %>" data-roll_number="<%= @student.roll_number %>">
    <span id="sendMessage" class="input-group-addon btn btn-primary">
        Send
    </span>
  </div>
</div>

<script src="https://player.vimeo.com/api/player.js"></script>
<script>
  document.addEventListener('contextmenu', event => event.preventDefault());
  document.onkeydown = function(e) {
    if(event.keyCode == 123) {
      return false;
    }
    if(e.ctrlKey && e.shiftKey && e.keyCode == 'I'.charCodeAt(0)){
      return false;
    }
    if(e.ctrlKey && e.shiftKey && e.keyCode == 'J'.charCodeAt(0)){
      return false;
    }
    if(e.ctrlKey && e.keyCode == 'U'.charCodeAt(0)){
      return false;
    }
    if(e.ctrlKey && e.shiftKey && e.keyCode == 'I'.charCodeAt(0)){
      return false;
    }
  }

  function setupActionCable() {
    App.video_chat = App.cable.subscriptions.create({channel: 'VideoChatChannel', id: "<%= @vimeo_live.id %>"}, {
      connected: function () {
        console.log("AC:: ACTION CABLE ==> Connected");
      },
      disconnected: function () {
        console.log("AC:: ACTION CABLE dis-connected");
      },
      received: function (data) {
        console.log("AC:: DATA => ", data);
        $(".msg-container").append(data.message);
        $(".msg-container").animate({ scrollTop: $('.msg-container').prop("scrollHeight")}, 1000);
      }
    });
  };

  $(document).ready(function(){
    <% if request.subdomain == 'bhargav' %>
      // setupActionCable();
    <% end %>

    $("#sendMessage").click(function(){
      var msg = $("#chatMessage").val();
      var name = $("#chatMessage").data("name");
      var roll_number = $("#chatMessage").data("roll_number");
      $("#chatMessage").val('');

      var formData = {
        message: msg,
        sender_name: "<%= @student.name %>",
        sender_type: 'Student',
        sender_id: "<%= @student.id %>",
        messageable_type: "<%= @vimeo_live&.class&.name %>",
        messageable_id: "<%= @vimeo_live&.id %>",
      };

      $.ajax({
        url : "/students/messages",
        type: "POST",
        data : formData,
        success: function(data, textStatus, jqXHR) {
          console.log("SUCCESS", data);
        },
        error: function (jqXHR, textStatus, errorThrown) {
          console.log("ERROR", errorThrown);
        }
      });

    });
  });
</script>


<style>
.msg-container {
  height: 400px;
  overflow-y: auto;
}
.student-msg {
  background-color: #bfbfbf;
  padding: 10px 5px 25px 5px;
  border-radius: 5px;
  margin: 10px 0px;
}
.admin-msg {
  background-color: #99cdf9;
  padding: 10px 5px 25px 5px;
  border-radius: 5px;
  margin: 10px 0px;
}
.time-right {
  float: right;
  color: #000;
}

.time-left {
  float: left;
  color: #000;
}
</style>;