config/routes.rb
Rails.application.routes.draw do
  devise_for :super_admins, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :admin
  devise_for :student

  mount ActionCable.server => '/cable'

  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == 'kapil' && password == 'kapil@7588584810'
  end
  mount Sidekiq::Web => '/sidekiq'

  post 'sync-attendance', to: 'admin/api/attendance#create'
  get  'machines', to: 'admin/api/attendance#machines'
  # mount PgHero::Engine, at: "/pg-stats-k"

  # authenticate :admin, -> (admin) { admin.present? } do
  #   mount PgHero::Engine, at: "pghero"
  # end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'students/home#index'

  get  'pay/:slug', to: 'pay#show'
  post 'pay', to: 'pay#create', as: :pay_path
  post 'process-pay', to: 'pay#process_pay', as: :pay_process_path
  post 'auth-pay', to: 'pay#auth_pay', as: :pay_auth_path

  post 'process-gform', to: 'students/google_forms#register'

  get 'new-admission', to: 'students/admissions#show'
  get 'registration', to: 'students/admissions#registration_form'
  post 'register', to: 'students/admissions#register'
  get 'registration-confirmation', to: 'students/admissions#registration_confirmation'
  get 'foundation-admission', to: 'students/admissions#foundation_show'
  get 'admission-done', to: 'students/admissions#admission_done'
  post 'admission-done', to: 'students/admissions#admission_done'
  post 'ADMISSION-DONE', to: 'students/admissions#admission_done'
  get 'ADMISSION-DONE', to: 'students/admissions#admission_done'
  get 'admission-done-set/:id', to: 'students/admissions#admission_done_set', as: :rcc_set_path

  # added for razorpay
  get 'initiate_pay', to: 'students/payments#initiate_pay', as: :initiate_pay
  post 'process-admission', to: 'students/payments#process_payment'
  post 'authorize_payment', to: 'students/payments#authorize_payment'
  get  'process-admission', to: 'students/payments#process_payment'
  get  'confirm_payment', to: 'students/payments#confirm_payment'

  get 'print-receipt/:reference_id', to: 'students/admissions#print_receipt'

  get 'pay-installment', to: 'students/admissions#pay_installment'
  get 'pay-due-fees', to: 'students/admissions#pay_due_fees'
  get 'pay_due_fees', to: 'students/admissions#pay_due_fees'

  namespace :students do
    get 'videos' => 'videos#lectures'
    get 'lectures' => 'videos#lectures'
    get 'lectures/:video_id' => 'videos#show_lecture'
    get 'lectures_tp/:tp_streams_id' => 'videos#show_lecture_tp'
    get 'category_videos/:id' => 'videos#category_videos'
    get 'yt-player' => 'videos#play_yt'
    get 'play-yt-video' => 'videos#play_yt_video'
    get 'otp_input', to: 'login#otp_input'
    post 'process_otp', to: 'login#process_otp'

    post 'authorise', to: 'login#authorise'
    get "auto-auth", to: 'home#auto_auth'
    root to: 'home#index'
    get :tests, to: 'home#tests', as: :tests
    get :progress_report, to: 'home#progress_report', as: :progress_report
    get :instructions, to: 'home#instructions', as: :exam_instructions
    get :confirmation, to: 'home#confirmation', as: :exam_confirmation
    get :question_bank, to: 'home#question_bank', as: :question_bank
    get :subscription, to: 'home#subscription', as: :exam_subscription
    get "summary/:exam_id", to: 'home#summary', as: :exam_summary
    # get :exam_data, to: 'home#exam_data'
    get :exam_data, to: 'exams#exam_data'
    get :exam_data_s3, to: 'exams#exam_data_s3'
    get :is_exam_valid, to: 'exams#is_exam_valid'
    get :print_hall_ticket, to: 'exams#print_hall_ticket'
    get "exam/:id", to: 'home#exam'
    put "sync/:exam_id/", to: 'home#sync'
    put "submit/:exam_id/", to: 'home#submit'
    resources :mock_tests
    get 'home/profile', to: 'home#profile'
    patch 'home/update_profile', to: 'home#update_profile'

    resources :model_answers
    resources :admissions do
      post :create_installment, on: :collection
    end
    resources :study_pdfs
    resources :notifications
    resources :progress_cards
    resources :messages
    resources :live_classes
  end


  # routes of admin panel
  namespace :admin do
    root to: 'dashboard#show'
    resource :dashboard
    resources :reports do
      get :exam_detailed_report
      get :generate_progress_report
    end
    resources :exams do
      collection do
        get 'question_bank', to: 'exams#question_bank'
        get 'new_jee', to: 'exams#new_jee'
        post 'change_question_answer'
        post :create_section
      end
      get :re_evaluate_exam
    end
    resources :practice_questions
    resources :students do
      root to: 'students#index'
      get   :import, on: :collection
      post  :process_import, on: :collection
      post  :process_import_fees_due, on: :collection
      get   :reset_login
      get   :disable
      get   :enable
      get   :progress_report
      get   :attendance_report
      post  :attendance_report
      post  :attendance_report_pdf
    end
    resources :batches do
      root to: 'batches#index'
      get   :disable
      get   :change_batches, on: :collection
      post  :process_change_batches, on: :collection
      get   :downoload_cet
    end
    resources :batch_groups

    get 'dashboard/profile', to: 'dashboard#profile'
    patch 'dashboard/update_profile', to: 'dashboard#update_profile'

    resources :video_lectures do
      get :chats
      get :student_video_views
      get :modity_student_views
    end
    resources :android_apps
    resources :users do
      get :profile, on: :collection
    end
    resources :study_pdfs
    resources :notifications
    resources :genres do
      get :hide
      get :show
      put :student_folder_access
    end
    resources :study_pdf_types
    resources :messages
    resources :zoom_meetings do
      get :chats
    end
    resources :subjects
    resources :omr
    resources :attendance do
      get :overview_report, on: :collection
      get :settings, on: :collection
      get :sms_logs, on: :collection
      post :change_auto_sms_settings, on: :collection
      post :send_batch_sms, on: :collection
      get :download_xls_report, on: :collection
      collection do
        resources :holidays
      end
    end

    resources :micro_payments
    resources :banners
    resources :att_machines do
      patch :enable
      patch :disable
    end

    resources :id_cards, only: [:index] do
      post :upload_photos, on: :collection
      get :print_cards, on: :collection
      post :print_cards, on: :collection
      post :generate_prints, on: :collection
    end

    namespace :api do
      resources :students
      resources :attendance
      resources :demo_logins

      # new admin api's for admin react front end.
      namespace :v2 do
        get 'get-token', to: 'auth#get_token'
        post 'login', to: 'auth#login'
        get 'fees-details', to: 'fees#details'
        get 'payment-history', to: 'fees#payment_history'
        post 'fees-transaction', to: 'fees#create_fees_transaction'
        get  'reports/collection', to: 'fees_reports#collection'
        get  'reports/collection_csv', to: 'fees_reports#collection_csv'
        get  'reports/due_fees', to: 'fees_reports#due_fees'
        get  'reports/due_fees_csv', to: 'fees_reports#due_fees_csv'
        get  'reports/notes', to: 'fees_reports#notes'
        get  'reports/print_status', to: 'fees_reports#print_status'
        post 'reports/set_print_status', to: 'fees_reports#set_print_status'
        get  'reports/pending-fees', to: 'fees_reports#pending_fees'
        get  'batches', to: 'batches#index'
        resources :students do
          get   :pending_amount, on: :collection
          get   :issued_notes
          post  :issue_notes
          post  :apply_discount
          get   :suggested_roll_number, on: :collection
          post  :change_course

          collection do
            resources :discounts, only: [:index, :create] do
              post :remove_discount, on: :collection
            end
          end
        end
        resources :notes
      end
    end
  end

  get 'current-server-time', to: 'home#current_server_time'

  namespace :api do
    namespace :v1 do
      post 'sign-in', to: 'students#login'
      post 'update-fcm-token', to: 'students#update_fcm_token'
      get  'is-form-registered', to: 'students#is_form_registered'
      get 'dashboard_data', to: 'home#dashboard_data'
      get 'gallery', to: 'home#gallery'
      get 'app-version', to: 'home#app_version'
      get 'categories', to: 'videos#categories'
      get 'categories/:id/videos', to: 'videos#category_videos'

      resources :notifications, only: [:index]
      resources :videos, only: [:index] do
        get   :get_yt_url
        post  :set_yt_url
        get   :need_url
        get   :get_ytdlp_url
        get   :get_ytdlp_url_from_youtube
      end
      resources :study_pdfs, only: [:index]
      resources :meetings, only: [:index]
      resources :trackers
    end

    # NEW ROUTES
    namespace :v2 do
      resources :students, only: [:index] do
        post 'login', on: :collection
        get  :progress_report, on: :collection
        post :register, on: :collection
        get  :de_active, on: :collection
      end
      resources :notifications
      resources :exams
      get 'subjects', to: 'subjects#index'
      get 'subjects/:id/folders', to: 'subjects#subject_folders'
      get 'subjects/:subject_id/folders/:folder_id/pdfs', to: 'subjects#folder_pdfs'
      get 'subjects/:subject_id/folders/:folder_id/videos', to: 'subjects#folder_videos'
      resources :videos, only: [] do
        post :like
        post :dislike

        get :comments
        post :add_comment
        post :remove_comment
        get :tp_streams_details
      end
    end
  end
end

app/views/layouts/admin/_dashboard_header.html.erb
<div class="header py-4">
  <div class="container">
    <div class="d-flex">
      <a class="header-brand" href="/">
      Smart Exams
      </a>
      <% if admin_signed_in? %>
        <div class="d-flex order-lg-2 ml-auto">
          <div class="dropdown">
            <a href="#" class="nav-link pr-0 leading-none" data-toggle="dropdown">
              <span class="avatar avatar-user-photo" ></span>
              <span class="ml-2 d-none d-lg-block">
                <span class="text-default"><%= current_admin.name%></span>
                <small class="text-muted d-block mt-1">Administrator</small>
              </span>
            </a>
            <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
              <%= link_to '<i class="dropdown-icon fa fa-user"></i> Profile'.html_safe, admin_dashboard_profile_path, class: 'dropdown-item' %>
              <a class="dropdown-item" href="#">
                <i class="dropdown-icon fa fa-settings"></i> Settings
              </a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">
                <i class="dropdown-icon fa fa-help-circle"></i> Need help?
              </a>
              <%= link_to '<i class="dropdown-icon fa fa-log-out"></i> Sign Out'.html_safe, destroy_admin_session_path, method: :delete, class:"dropdown-item"%>
            </div>
          </div>
        </div>
      <% end %>
      <a href="#" class="header-toggler d-lg-none ml-3 ml-lg-0" data-toggle="collapse" data-target="#headerMenuCollapse">
        <span class="header-toggler-icon"></span>
      </a>
    </div>
  </div>
</div>
<div class="header collapse d-lg-flex p-0" id="headerMenuCollapse">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg order-lg-first">
        <ul class="nav nav-tabs border-0 flex-column flex-lg-row">
          <li class="nav-item">
            <a href="#" class="nav-link" data-toggle="dropdown"><i class="fa fa-box"></i> Data</a>
             <div class="dropdown-menu dropdown-menu-arrow">
              <%= link_to ' Manage Students', admin_students_path, class: 'dropdown-item' %>
              <%= link_to ' Manage Batches', admin_batches_path, class: 'dropdown-item' %>
            </div>
          </li>
          <li class="nav-item">
            <%= link_to '<i class="fa fa-chart-bar"></i> Reports'.html_safe, admin_reports_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to '<i class="fa fa-desktop"></i> Exams'.html_safe, admin_exams_path, class: 'nav-link' %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

<%# check icons here https://fontawesome.com/ %>

app/views/layouts/admin/_dashboard_header_new.html.erb
<% 
  refresh_token = SecureRandom.uuid
  REDIS_CACHE.set(refresh_token, current_admin.id, { ex: 10.minutes })
  base_url = request.host_with_port
  fees_host = Rails.env.production? ? "https://fees-app.eduaakar.com" : "http://localhost:3002"
%>
<div class="header py-4">
  <div class="container">
    <div class="d-flex">
      <a class="header-brand" href="/">
        <% if @current_org.data.dig('name_and_logo', 'logo').present? %>
          <%= image_tag @current_org.data.dig('name_and_logo', 'logo') %>
        <% end %>
        <%= @current_org&.name %>
      </a>
      <% if admin_signed_in? %>
        <div class="d-flex order-lg-2 ml-auto">
          <div class="dropdown">
            <a href="#" class="nav-link pr-0 leading-none" data-toggle="dropdown">
              <span class="avatar avatar-user-photo" ></span>
              <span class="ml-2 d-none d-lg-block">
                <span class="text-default"><%= current_admin.name %></span>
                <small class="text-muted d-block mt-1">Administrator</small>
              </span>
            </a>
            <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
              <a class="dropdown-item" href="#">
                <i class="dropdown-icon fa fa-user"></i> Profile
              </a>
              <a class="dropdown-item" href="<%= profile_admin_users_path %>">
                <i class="dropdown-icon fa fa-settings"></i> Settings
              </a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">
                <i class="dropdown-icon fa fa-help-circle"></i> Need help?
              </a>
              <%= link_to '<i class="dropdown-icon fa fa-log-out"></i> Sign Out'.html_safe, destroy_admin_session_path, method: :delete, class:"dropdown-item"%>
            </div>
          </div>
        </div>
      <% end %>
      <a href="#" class="header-toggler d-lg-none ml-3 ml-lg-0" data-toggle="collapse" data-target="#headerMenuCollapse">
        <span class="header-toggler-icon"></span>
      </a>
    </div>
  </div>
</div>
<div class="header collapse d-lg-flex p-0" id="headerMenuCollapse">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg order-lg-first">
        <ul class="nav nav-tabs border-0 flex-column flex-lg-row">
          <li class="nav-item">
            <% if current_admin.can_manage(:students) %>
              <%= link_to '<i class="fa fa-users"></i> Students'.html_safe, admin_students_path, class: current_page?(admin_students_path) ? "nav-link active" : "nav-link" %>
            <% end %>
          </li>
          <% if current_admin.can_manage(:batches) %>
            <li class="nav-item">
              <a class="<%= current_page?(admin_batches_path) ? 'dropdown-toggle nav-link active' : 'dropdown-toggle nav-link' %>" type="button" id="dropdownMenu1" data-toggle="dropdown">
                <i class="fas fa-tools"></i> Batches
              </a>
              <div class="dropdown-menu">
                <%= link_to '<i class="fa fa-list"></i> Batches'.html_safe, admin_batches_path, class: "dropdown-item"%>
                <%= link_to '<i class="fa fa-sitemap"></i> Batch Groups'.html_safe, admin_batch_groups_path, class: "dropdown-item"%>
              </div>
            </li>
          <% end %>
          <% if current_admin.can_manage(:subjects) %>
            <li class="nav-item">
              <%= link_to '<i class="fa fa-list"></i> Subjects'.html_safe, admin_subjects_path, class: current_page?(admin_subjects_path) ? "nav-link active" : "nav-link" %>
            </li>
          <% end %>
          <% if current_admin.can_manage(:reports) %>
            <li class="nav-item">
              <%= link_to '<i class="fa fa-chart-bar"></i> Reports'.html_safe, admin_reports_path, class: current_page?(admin_reports_path) ? "nav-link active" : "nav-link" %>
            </li>
          <% end %>
          <% if current_admin.can_manage(:exams) %>
            <li class="nav-item">
              <%= link_to '<i class="fa fa-paste"></i> Exams'.html_safe, admin_exams_path, class: current_page?(admin_exams_path) ? "nav-link active" : "nav-link" %>
            </li>
          <% end %>
          <% if current_admin.can_manage(:videos) %>
            <li class="nav-item">
              <%= link_to '<i class="fa fa-photo-video"></i> Videos Portal'.html_safe, admin_video_lectures_path, class: current_page?(admin_video_lectures_path) ? "nav-link active" : "nav-link" %>
            </li>
          <% end %>
          <li class="nav-item">
            <a class="<%= current_page?(admin_android_apps_path) ? 'dropdown-toggle nav-link active' : 'dropdown-toggle nav-link' %>" type="button" id="dropdownMenu1" data-toggle="dropdown">
              <i class="fa fa-mobile-alt"></i> Android APP
            </a>
            <div class="dropdown-menu">
              <% if current_admin.can_manage(:notifications) %>
                <a class="dropdown-item" href="<%= admin_notifications_path %>">Notifications</a>
              <% end %>
              <% if current_admin.can_manage(:live_classes) %>
                <a class="dropdown-item" href="<%= admin_zoom_meetings_path %>">Live Classes</a>
              <% end %>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="<%= admin_banners_path %>">Top Banners</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="<%= admin_genres_path %>">App folders</a>
            </div>
          </li>
          <% if current_admin.can_manage(:omr) %>
            <li class="nav-item">
            <a class="<%= current_page?(admin_omr_index_path) ? 'dropdown-toggle nav-link active' : 'dropdown-toggle nav-link' %>" type="button" id="dropdownMenu1" data-toggle="dropdown">
              <i class="fa fa-address-card"></i> OMR
            </a>
            <div class="dropdown-menu">
              <% if current_admin.can_manage(:omr) %>
                <%= link_to '<i class="fa fa-list"></i> Import'.html_safe, admin_omr_index_path, class: "dropdown-item"%>
              <% end %>
              <% if current_admin.can_manage(:omr) %>
                <%= link_to '<i class="fa fa-file"></i> Reports'.html_safe, reports_admin_omr_index_path, class: "dropdown-item"%>
              <% end %>
            </div>
          </li>
          <% end %>
          <li class="nav-item">
            <a class="<%= current_page?(admin_attendance_index_path) ? 'dropdown-toggle nav-link active' : 'dropdown-toggle nav-link' %>" type="button" id="dropdownMenu1" data-toggle="dropdown">
              <i class="fa fa-list"></i> ATT
            </a>
            <div class="dropdown-menu">
              <% if current_admin.can_manage(:attendance) %>
                <%= link_to '<i class="fa fa-list"></i> Attendance'.html_safe, admin_attendance_index_path, class: "dropdown-item"%>
              <% end %>
              <% if current_admin.can_manage(:attendance) %>
                <%= link_to '<i class="fa fa-envelope"></i> SMS Log'.html_safe, sms_logs_admin_attendance_index_path, class: "dropdown-item"%>
              <% end %>
              <% if current_admin.can_manage(:attendance) %>
                <%= link_to '<i class="fas fa-tools"></i> Holidays'.html_safe, admin_holidays_path, class: "dropdown-item"%>
              <% end %>
            </div>
          </li>
          <li class="nav-item">
            <a class="<%= current_page?(admin_android_apps_path) ? 'dropdown-toggle nav-link active' : 'dropdown-toggle nav-link' %>" type="button" id="dropdownMenu1" data-toggle="dropdown">
              <i class="fas fa-tools"></i> Administration
            </a>
            <div class="dropdown-menu">
              <% if current_admin.can_manage(:admin_users) %>
                <%= link_to '<i class="fa fa-users"></i> Admin Users'.html_safe, admin_users_path, class: "dropdown-item"%>
              <% end %>
              <% if current_admin.can_manage(:payments) %>
                <%= link_to '<i class="fas fa-rupee-sign"></i> Payments'.html_safe, admin_micro_payments_path, class: "dropdown-item"%>
              <% end %>
              <% if current_admin.can_manage(:students) %>
                <%= link_to '<i class="fas fa-user"></i> Student Id Cards'.html_safe, admin_id_cards_path, class: "dropdown-item"%>
              <% end %>
              <% if current_admin.can_manage(:discounts) %>
                <%= link_to '<i class="fas fa-user"></i> Import Discounts'.html_safe, admin_discounts_path, class: "dropdown-item"%>
              <% end %>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/admin/dashboard.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= get_header_name(request.subdomain) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css">
  </head>
  <body>
    <div class="page">
      <div class="page-main">
      <%= render 'layouts/admin/dashboard_header_new' %>
        <div class="my-3 my-md-5">
          <div class="container">
            <% flash.each do |key, value| %>
              <div id="alert" class="alert alert-<%= key == 'success' ? 'success' : 'danger' %>">
                <%= value %>
              </div>
            <% end %>
              <%= yield %>
          </div>
        </div>
      </div>
    </div>
    <script type="text/javascript">
      $(function(){
        $('#alert').fadeIn(1000).delay(2500).fadeOut(2000);
      });
    </script>
  </body>
</html>