config/routes.rb
Rails.application.routes.draw do
  devise_for :super_admins, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :admin
  devise_for :student

  mount ActionCable.server => '/cable'

  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == 'kapil' && password == 'kapil@7588584810'
  end
  mount Sidekiq::Web => '/sidekiq'

  post 'sync-attendance', to: 'admin/api/attendance#create'
  get  'machines', to: 'admin/api/attendance#machines'
  # mount PgHero::Engine, at: "/pg-stats-k"

  # authenticate :admin, -> (admin) { admin.present? } do
  #   mount PgHero::Engine, at: "pghero"
  # end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'students/home#index'

  get  'pay/:slug', to: 'pay#show'
  post 'pay', to: 'pay#create', as: :pay_path
  post 'process-pay', to: 'pay#process_pay', as: :pay_process_path
  post 'auth-pay', to: 'pay#auth_pay', as: :pay_auth_path

  post 'process-gform', to: 'students/google_forms#register'

  get 'new-admission', to: 'students/admissions#show'
  get 'registration', to: 'students/admissions#registration_form'
  post 'register', to: 'students/admissions#register'
  get 'registration-confirmation', to: 'students/admissions#registration_confirmation'
  get 'foundation-admission', to: 'students/admissions#foundation_show'
  get 'admission-done', to: 'students/admissions#admission_done'
  post 'admission-done', to: 'students/admissions#admission_done'
  post 'ADMISSION-DONE', to: 'students/admissions#admission_done'
  get 'ADMISSION-DONE', to: 'students/admissions#admission_done'
  get 'admission-done-set/:id', to: 'students/admissions#admission_done_set', as: :rcc_set_path

  # added for razorpay
  get 'initiate_pay', to: 'students/payments#initiate_pay', as: :initiate_pay
  post 'process-admission', to: 'students/payments#process_payment'
  post 'authorize_payment', to: 'students/payments#authorize_payment'
  get  'process-admission', to: 'students/payments#process_payment'
  get  'confirm_payment', to: 'students/payments#confirm_payment'

  get 'print-receipt/:reference_id', to: 'students/admissions#print_receipt'

  get 'pay-installment', to: 'students/admissions#pay_installment'
  get 'pay-due-fees', to: 'students/admissions#pay_due_fees'
  get 'pay_due_fees', to: 'students/admissions#pay_due_fees'

  namespace :students do
    get 'videos' => 'videos#lectures'
    get 'lectures' => 'videos#lectures'
    get 'lectures/:video_id' => 'videos#show_lecture'
    get 'lectures_tp/:tp_streams_id' => 'videos#show_lecture_tp'
    get 'category_videos/:id' => 'videos#category_videos'
    get 'yt-player' => 'videos#play_yt'
    get 'play-yt-video' => 'videos#play_yt_video'
    get 'otp_input', to: 'login#otp_input'
    post 'process_otp', to: 'login#process_otp'

    post 'authorise', to: 'login#authorise'
    get "auto-auth", to: 'home#auto_auth'
    root to: 'home#index'
    get :tests, to: 'home#tests', as: :tests
    get :progress_report, to: 'home#progress_report', as: :progress_report
    get :instructions, to: 'home#instructions', as: :exam_instructions
    get :confirmation, to: 'home#confirmation', as: :exam_confirmation
    get :question_bank, to: 'home#question_bank', as: :question_bank
    get :subscription, to: 'home#subscription', as: :exam_subscription
    get "summary/:exam_id", to: 'home#summary', as: :exam_summary
    # get :exam_data, to: 'home#exam_data'
    get :exam_data, to: 'exams#exam_data'
    get :exam_data_s3, to: 'exams#exam_data_s3'
    get :is_exam_valid, to: 'exams#is_exam_valid'
    get :print_hall_ticket, to: 'exams#print_hall_ticket'
    get "exam/:id", to: 'home#exam'
    put "sync/:exam_id/", to: 'home#sync'
    put "submit/:exam_id/", to: 'home#submit'
    resources :mock_tests
    get 'home/profile', to: 'home#profile'
    patch 'home/update_profile', to: 'home#update_profile'

    resources :model_answers
    resources :admissions do
      post :create_installment, on: :collection
    end
    resources :study_pdfs
    resources :notifications
    resources :progress_cards
    resources :messages
    resources :live_classes
  end


  # routes of admin panel
  namespace :admin do
    root to: 'dashboard#show'
    resource :dashboard
    resources :reports do
      get :exam_detailed_report
      get :generate_progress_report
    end
    resources :exams do
      collection do
        get 'question_bank', to: 'exams#question_bank'
        get 'new_jee', to: 'exams#new_jee'
        post 'change_question_answer'
        post :create_section
      end
      get :re_evaluate_exam
    end
    resources :practice_questions
    resources :students do
      root to: 'students#index'
      get   :import, on: :collection
      post  :process_import, on: :collection
      post  :process_import_fees_due, on: :collection
      get   :reset_login
      get   :disable
      get   :enable
      get   :progress_report
      get   :attendance_report
      post  :attendance_report
      post  :attendance_report_pdf
    end
    resources :batches do
      root to: 'batches#index'
      get   :disable
      get   :change_batches, on: :collection
      post  :process_change_batches, on: :collection
      get   :downoload_cet
    end
    resources :batch_groups

    get 'dashboard/profile', to: 'dashboard#profile'
    patch 'dashboard/update_profile', to: 'dashboard#update_profile'

    resources :video_lectures do
      get :chats
      get :student_video_views
      get :modity_student_views
    end
    resources :android_apps
    resources :users do
      get :profile, on: :collection
    end
    resources :study_pdfs
    resources :notifications
    resources :genres do
      get :hide
      get :show
      put :student_folder_access
    end
    resources :study_pdf_types
    resources :messages
    resources :zoom_meetings do
      get :chats
    end
    resources :subjects
    resources :omr
    resources :attendance do
      get :overview_report, on: :collection
      get :settings, on: :collection
      get :sms_logs, on: :collection
      post :change_auto_sms_settings, on: :collection
      post :send_batch_sms, on: :collection
      get :download_xls_report, on: :collection
      collection do
        resources :holidays
      end
    end

    resources :micro_payments
    resources :banners
    resources :att_machines do
      patch :enable
      patch :disable
    end

    resources :id_cards, only: [:index] do
      post :upload_photos, on: :collection
      get :print_cards, on: :collection
      post :print_cards, on: :collection
      post :generate_prints, on: :collection
    end

    namespace :api do
      resources :students
      resources :attendance
      resources :demo_logins

      # new admin api's for admin react front end.
      namespace :v2 do
        get 'get-token', to: 'auth#get_token'
        post 'login', to: 'auth#login'
        get 'fees-details', to: 'fees#details'
        get 'payment-history', to: 'fees#payment_history'
        post 'fees-transaction', to: 'fees#create_fees_transaction'
        get  'reports/collection', to: 'fees_reports#collection'
        get  'reports/collection_csv', to: 'fees_reports#collection_csv'
        get  'reports/due_fees', to: 'fees_reports#due_fees'
        get  'reports/due_fees_csv', to: 'fees_reports#due_fees_csv'
        get  'reports/notes', to: 'fees_reports#notes'
        get  'reports/print_status', to: 'fees_reports#print_status'
        post 'reports/set_print_status', to: 'fees_reports#set_print_status'
        get  'reports/pending-fees', to: 'fees_reports#pending_fees'
        get  'batches', to: 'batches#index'
        resources :students do
          get   :pending_amount, on: :collection
          get   :issued_notes
          post  :issue_notes
          post  :apply_discount
          get   :suggested_roll_number, on: :collection
          post  :change_course

          collection do
            resources :discounts, only: [:index, :create] do
              post :remove_discount, on: :collection
            end
          end
        end
        resources :notes
      end
    end
  end

  get 'current-server-time', to: 'home#current_server_time'

  namespace :api do
    namespace :v1 do
      post 'sign-in', to: 'students#login'
      post 'update-fcm-token', to: 'students#update_fcm_token'
      get  'is-form-registered', to: 'students#is_form_registered'
      get 'dashboard_data', to: 'home#dashboard_data'
      get 'gallery', to: 'home#gallery'
      get 'app-version', to: 'home#app_version'
      get 'categories', to: 'videos#categories'
      get 'categories/:id/videos', to: 'videos#category_videos'

      resources :notifications, only: [:index]
      resources :videos, only: [:index] do
        get   :get_yt_url
        post  :set_yt_url
        get   :need_url
        get   :get_ytdlp_url
        get   :get_ytdlp_url_from_youtube
      end
      resources :study_pdfs, only: [:index]
      resources :meetings, only: [:index]
      resources :trackers
    end

    # NEW ROUTES
    namespace :v2 do
      resources :students, only: [:index] do
        post 'login', on: :collection
        get  :progress_report, on: :collection
        post :register, on: :collection
        get  :de_active, on: :collection
      end
      resources :notifications
      resources :exams
      get 'subjects', to: 'subjects#index'
      get 'subjects/:id/folders', to: 'subjects#subject_folders'
      get 'subjects/:subject_id/folders/:folder_id/pdfs', to: 'subjects#folder_pdfs'
      get 'subjects/:subject_id/folders/:folder_id/videos', to: 'subjects#folder_videos'
      resources :videos, only: [] do
        post :like
        post :dislike

        get :comments
        post :add_comment
        post :remove_comment
        get :tp_streams_details
      end
    end
  end
end

app/controllers/admin/reports_controller.rb
class Admin::ReportsController < Admin::BaseController
  before_action :check_permissions

  ITEMS_PER_PAGE = 20
  USE_CACHE = false

  def index
    @exams = Exam.where(org: current_org).includes(:batches, :exam_sections, :exam_batches).where(batches: {id: current_admin.batches&.ids}).all.order(id: :desc)
    @students_count_by_exam_id = StudentExam.where(exam: @exams).group(:exam_id).count

    @exams = @exams.page(params[:page]).per(params[:limit] || ITEMS_PER_PAGE)
  end

  def generate_progress_report
    exam = Exam.find_by(id: params[:report_id], org: current_org)
    if exam.present?
      flash[:success] = "Report Card will get generated in background, Do not Regenrate it."
      ProgressReportWorker.perform_async(exam.id)
      REDIS_CACHE.set("pr-report-exam-id-#{exam.id}", true, { ex: 1.hour })
    else
      flash[:error] = "Invalid Exam, please try again."
    end

    redirect_to admin_reports_path
  end

  def show
    exam = Exam.find_by(id: params[:id], org: current_org)
    exam_csv_redis_key = "exam-csv-report-#{exam.id}"
    @response = USE_CACHE ? REDIS_CACHE.get(exam_csv_redis_key): nil
    if @response.blank?
      @response = Reports::ExamCsvReportService.new(params[:id]).prepare_report
      # store response in cache if exam expired
      if exam.exam_available_till.present? && exam.exam_available_till + 5.hours < Time.current
        REDIS_CACHE.set(exam_csv_redis_key, @response, { ex: 1.day })
      end
    else
      puts "\n\n\n\n\n ===========================> exam-csv-report cache suceeded \n\n\n\n"
    end

    respond_to do |format|
      format.html do
        set_flash
      end
      format.pdf do
        render pdf: "student information",
               template: "admin/reports/show.pdf.erb",
               locals: {students: @response[:student_exams]},
               footer: { font_size: 9, left: DateTime.now.strftime("%d-%B-%Y %I:%M%p"), right: 'Page [page] of [topage]' }
      end
      format.csv do
        send_data @response, filename: "#{exam.name.parameterize}_result.csv"
      end
    end
  end

  def exam_detailed_report
    exam = Exam.find_by(id: params[:report_id], org: current_org)

    exam_detailed_redis_key = "exam-detailed-csv-report-#{exam.id}"
    @response = USE_CACHE ? REDIS_CACHE.get(exam_detailed_redis_key) : nil
    if @response.blank?
      @response = Reports::DetailedExamCsvReportService.new(exam.id).prepare_report
      # store response in cache if exam expired
      if exam.exam_available_till.present? && exam.exam_available_till + 5.hours < Time.current
        REDIS_CACHE.set(exam_detailed_redis_key, @response, { ex: 2.minutes })
      end
    else
      puts "\n\n\n\n\n ===========================> exam-csv-report cache suceeded \n\n\n\n"
    end

    respond_to do |format|
      format.csv do
        send_data @response, filename: "#{exam.name.parameterize}_detailed_student_analysis_report.csv"
      end
    end
  end

  private

  def set_flash
    unless @response[:status]
      flash[:error] = @response[:message]
    end
  end

  def check_permissions
    redirect_to '/404' unless current_admin.can_manage(:reports)
  end
end

app/helpers/admin/reports_helper.rb
module Admin::ReportsHelper
end

app/views/admin/reports/index.html.erb
<div class="row">
  <div class="col-12">
    <div class="card">
      <div class="card-header">
        <div class="col-md-2">
          <h5 class="pt-3"> Reports</h5>
        </div>
      </div>
      <div class="card-body">
        <div class="table-responsive">
          <table class="table table-striped table-bordered">
            <thead>
            <tr>
              <th>Name</th>
              <th>Info (Q|Marks|Stds)</th>
              <th>Exam Date</th>
              <th>Progress Report</th>
              <th style="width: 170px;">Download Reports</th>
            </tr>
            </thead>
            <tbody>
              <% if @exams.present? %>
                <% @exams.each do |exam| %>
                  <tr>
                    <td>
                      <%= link_to "#{exam.name}", admin_exam_path(exam.id) %>
                      <br />
                      <span style="font-size: 10px"><%= exam.batches.pluck(:name).join(', ').slice(0..90) %></span>
                    </td>
                    <td>
                      <span>
                        <%= "#{exam.no_of_questions} | #{exam.total_marks} | " %>
                        <b style="color: green"><%= @students_count_by_exam_id[exam.id]%></b>
                      </span>
                    </td>
                    <td style="font-size: 12px"><%= exam.show_exam_at.strftime("%d-%b-%y %I:%M %p") %> </td>
                    <td class="text-center">
                      <% if REDIS_CACHE&.get("pr-report-exam-id-#{exam.id}") == 'true' %>
                        <span style="color: peru">
                          <i class="fas fa-sync fa-spin fa-2x"></i>
                        </span>
                      <% else %>
                        <% if exam.is_pr_generated %>
                          <span style="color: green">
                            <i class="far fa-check-circle fa-2x"></i>
                          </span>
                        <% else %>
                          <%= link_to 'Generate', admin_report_generate_progress_report_path(exam), class: "btn btn-sm btn-outline-primary", 'data-toggle': 'tooltip', title: 'GENERATE REPORT', data: {confirm: 'Are you sure, You want to Generate Progress report, Once generated it cannot be updated.'} %> <br />
                          <span style="color: red">Auto tonight</span>
                        <% end %>
                      <% end %>
                    </td>
                    <td class="text-center">
                      <%= link_to 'Summary', admin_report_path(exam, format: 'csv'), class: 'btn btn-sm btn-outline-secondary' %>
                      <%= link_to 'Detailed', admin_report_exam_detailed_report_path(exam, format: 'csv'), class: 'btn btn-sm btn-outline-secondary' %>
                    </td>
                  </tr>
                <% end %>
              <% else %>
                <tr>
                  <td colspan="8" class="text-center">No exams found, Add exams </td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <%= paginate @exams %>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- you need to include the shieldui css and js assets in order for the components to work -->
<link rel="stylesheet" type="text/css" href="http://www.shieldui.com/shared/components/latest/css/light/all.min.css" />
<script type="text/javascript" src="http://www.shieldui.com/shared/components/latest/js/shieldui-all.min.js"></script>
<script type="text/javascript" src="http://www.shieldui.com/shared/components/latest/js/jszip.min.js"></script>

<script type="text/javascript">
  jQuery(function ($) {
    $("#exportButton").click(function () {
      // parse the HTML table element having an id=exportTable
      var dataSource = shield.DataSource.create({
        data: "#exportTable",
        schema: {
          type: "table",
          fields: {
            SrNo: {type: String},
            StudentName: {type: String},
            Batch: {type: String},
            Marks: {type: String},
            rank: {type: String},
            correct: {type: String},
            wrong: {type: String},
          }
        }
      });

      // when parsing is done, export the data to PDF
      dataSource.read().then(function (data) {
        var pdf = new shield.exp.PDFDocument({
          author: "PrepBootstrap",
          created: new Date()
        });

        pdf.addPage("a4", "portrait");

        pdf.table(
          5,
          5,
          data,
          [
            {field: "SrNo", title: "Sr NO.", width: 50},
            {field: "StudentName", title: "Student ", width: 200},
            {field: "Batch", title: "Batch", width: 100},
            {field: "Marks", title: "Marks ", width: 50},
            {field: "rank", title: "rank", width: 50},
            {field: "correct", title: "correct ", width: 50},
            {field: "wrong" , title: "correct ", width: 50},
          ],
          {
            margins: {
              top: 50,
              left: 2
            }
          }
        );

        pdf.saveAs({
          fileName: "StudentReport"
        });
      });
    });
  });
</script>

<style>
  #exportButton {
    border-radius: 0;
  }
</style>

app/views/admin/reports/index.pdf.erb
<div class="col-12">
  <div class="card" style="border: none;">
    <div class="card-header text-center">
      <h4>Munde Coaching Classes</h4>
      <p>Nanded.</p>
    </div>
      <table class="table table-bordered table-vcenter text-nowrap">
        <thead>
          <tr>
            <th>SrNo</th>
            <th>StudentName</th>
            <th>Batch</th>
            <th>Marks</th>
            <th>rank</th>
            <th>correct</th>
            <th>wrong</th>
          </tr>
        </thead>
        <tbody>
          <% @students.each do |student| %>
            <tr>
              <% total = 90 %>
              <% correct = student[:marks]/2 %>
              <td><%= student[:id] %></td>
              <td><%= student[:name] %></td>
              <td><%= student[:batch] %></td>
              <td><%= student[:marks] %></td>
              <td><%= student[:rank] %></td>
              <td><%= correct %></td>
              <td><%= total - correct %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
  </div>
</div>

app/views/admin/reports/show.html.erb
<div class="row">
  <div class="col-12">
    <div class="card">
      <div class="card-header">
        <h5>Exam Reports</h5>
      </div>
      <div class="card-body">
        <% if @response[:status] %>
          <div class="col-12 text-right">
            <button class="btn btn-danger btn-sm clearfix">
              <span class="fa fa-file-pdf-o"></span>
              <%= link_to 'PDF', admin_report_path(request.parameters.merge({format: :pdf})), target: '_blank', class: 'text-white no-underline'%>
            </button>
            <button class="btn btn-success clearfix btn-sm">
              <span class="fa fa-file-text-o"></span>
              <%= link_to 'CSV'.html_safe, admin_report_path(request.parameters.merge({format: :csv})), target: '_blank', class: 'text-white no-underline'%>
            </button>
          </div>
          <div class="col-12">
            <div class="table-responsive mt-3">
              <table id="exportTable" class="table table-striped table-bordered">
                <thead>
                  <tr>
                    <th><%= sort_link(@response[:search], :student_id) %></th>
                    <th>Student Name</th>
                    <th>Score</th>
                    <th><%= sort_link(@response[:search], :rank) %></th>
                    <th>Correct</th>
                    <th>Wrong</th>
                  </tr>
                </thead>
                <tbody>
                  <% @response[:student_exam_summaries_hash].each do |student_exam_summary| %>
                    <tr>
                      <td><%= student_exam_summary[:roll_number] %></td>
                      <td><%= student_exam_summary[:name] %></td>
                      <td><%= student_exam_summary[:score] %></td>
                      <td><%= student_exam_summary[:rank] %></td>
                      <td><%= student_exam_summary[:correct] %></td>
                      <td><%= student_exam_summary[:incorrect] %></td>
                    </tr>
                  <% end  %>
                </tbody>
              </table>
            </div>
        </div>
        <% else %>
          <div class="well text-center">
            Nothing here yet. Seems no results are present.
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>


<!-- you need to include the shieldui css and js assets in order for the components to work -->
<link rel="stylesheet" type="text/css" href="http://www.shieldui.com/shared/components/latest/css/light/all.min.css" />
<script type="text/javascript" src="http://www.shieldui.com/shared/components/latest/js/shieldui-all.min.js"></script>
<script type="text/javascript" src="http://www.shieldui.com/shared/components/latest/js/jszip.min.js"></script>

<script type="text/javascript">
  jQuery(function ($) {
    $("#exportButton").click(function () {
      // parse the HTML table element having an id=exportTable
      var dataSource = shield.DataSource.create({
        data: "#exportTable",
        schema: {
          type: "table",
          fields: {
            SrNo: {type: String},
            StudentName: {type: String},
            Batch: {type: String},
            Marks: {type: String},
            rank: {type: String},
            correct: {type: String},
            wrong: {type: String},
          }
        }
      });

      // when parsing is done, export the data to PDF
      dataSource.read().then(function (data) {
        var pdf = new shield.exp.PDFDocument({
          author: "PrepBootstrap",
          created: new Date()
        });

        pdf.addPage("a4", "portrait");

        pdf.table(
          5,
          5,
          data,
          [
            {field: "SrNo", title: "Sr NO.", width: 50},
            {field: "StudentName", title: "Student ", width: 200},
            {field: "Batch", title: "Batch", width: 100},
            {field: "Marks", title: "Marks ", width: 50},
            {field: "rank", title: "rank", width: 50},
            {field: "correct", title: "correct ", width: 50},
            {field: "wrong" , title: "correct ", width: 50},
          ],
          {
            margins: {
              top: 50,
              left: 2
            }
          }
        );

        pdf.saveAs({
          fileName: "StudentReport"
        });
      });
    });
  });
</script>

<style>
  #exportButton {
    border-radius: 0;
  }
</style>

app/views/admin/reports/show.pdf.erb
<div class="col-12">
  <div class="card border-0">
    <div class="card-header text-center border-0">
      <h4></h4>
    </div>
      <table class="table table-striped table-vcenter text-nowrap">
        <thead>
          <tr>
            <th>Roll Number</th>
            <th>StudentName</th>
            <th>Marks</th>
            <th>Rank</th>
            <th>correct</th>
            <th>wrong</th>
          </tr>
        </thead>
        <tbody>
          <% @response[:student_exam_summaries_hash].each do |student_exam_summary| %>
            <tr>
              <td><%= student_exam_summary[:roll_number] %></td>
              <td><%= student_exam_summary[:name] %></td>
              <td><%= student_exam_summary[:score] %></td>
              <td><%= student_exam_summary[:rank] %></td>
              <td><%= student_exam_summary[:correct] %></td>
              <td><%= student_exam_summary[:incorrect] %></td>
            </tr>
          <% end  %>
        </tbody>
      </table>
  </div>
</div>