config/routes.rb
Rails.application.routes.draw do
  devise_for :super_admins, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :admin
  devise_for :student

  mount ActionCable.server => '/cable'

  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == 'kapil' && password == 'kapil@7588584810'
  end
  mount Sidekiq::Web => '/sidekiq'

  post 'sync-attendance', to: 'admin/api/attendance#create'
  get  'machines', to: 'admin/api/attendance#machines'
  # mount PgHero::Engine, at: "/pg-stats-k"

  # authenticate :admin, -> (admin) { admin.present? } do
  #   mount PgHero::Engine, at: "pghero"
  # end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'students/home#index'

  get  'pay/:slug', to: 'pay#show'
  post 'pay', to: 'pay#create', as: :pay_path
  post 'process-pay', to: 'pay#process_pay', as: :pay_process_path
  post 'auth-pay', to: 'pay#auth_pay', as: :pay_auth_path

  post 'process-gform', to: 'students/google_forms#register'

  get 'new-admission', to: 'students/admissions#show'
  get 'registration', to: 'students/admissions#registration_form'
  post 'register', to: 'students/admissions#register'
  get 'registration-confirmation', to: 'students/admissions#registration_confirmation'
  get 'foundation-admission', to: 'students/admissions#foundation_show'
  get 'admission-done', to: 'students/admissions#admission_done'
  post 'admission-done', to: 'students/admissions#admission_done'
  post 'ADMISSION-DONE', to: 'students/admissions#admission_done'
  get 'ADMISSION-DONE', to: 'students/admissions#admission_done'
  get 'admission-done-set/:id', to: 'students/admissions#admission_done_set', as: :rcc_set_path

  # added for razorpay
  get 'initiate_pay', to: 'students/payments#initiate_pay', as: :initiate_pay
  post 'process-admission', to: 'students/payments#process_payment'
  post 'authorize_payment', to: 'students/payments#authorize_payment'
  get  'process-admission', to: 'students/payments#process_payment'
  get  'confirm_payment', to: 'students/payments#confirm_payment'

  get 'print-receipt/:reference_id', to: 'students/admissions#print_receipt'

  get 'pay-installment', to: 'students/admissions#pay_installment'
  get 'pay-due-fees', to: 'students/admissions#pay_due_fees'
  get 'pay_due_fees', to: 'students/admissions#pay_due_fees'

  namespace :students do
    get 'videos' => 'videos#lectures'
    get 'lectures' => 'videos#lectures'
    get 'lectures/:video_id' => 'videos#show_lecture'
    get 'lectures_tp/:tp_streams_id' => 'videos#show_lecture_tp'
    get 'category_videos/:id' => 'videos#category_videos'
    get 'yt-player' => 'videos#play_yt'
    get 'play-yt-video' => 'videos#play_yt_video'
    get 'otp_input', to: 'login#otp_input'
    post 'process_otp', to: 'login#process_otp'

    post 'authorise', to: 'login#authorise'
    get "auto-auth", to: 'home#auto_auth'
    root to: 'home#index'
    get :tests, to: 'home#tests', as: :tests
    get :progress_report, to: 'home#progress_report', as: :progress_report
    get :instructions, to: 'home#instructions', as: :exam_instructions
    get :confirmation, to: 'home#confirmation', as: :exam_confirmation
    get :question_bank, to: 'home#question_bank', as: :question_bank
    get :subscription, to: 'home#subscription', as: :exam_subscription
    get "summary/:exam_id", to: 'home#summary', as: :exam_summary
    # get :exam_data, to: 'home#exam_data'
    get :exam_data, to: 'exams#exam_data'
    get :exam_data_s3, to: 'exams#exam_data_s3'
    get :is_exam_valid, to: 'exams#is_exam_valid'
    get :print_hall_ticket, to: 'exams#print_hall_ticket'
    get "exam/:id", to: 'home#exam'
    put "sync/:exam_id/", to: 'home#sync'
    put "submit/:exam_id/", to: 'home#submit'
    resources :mock_tests
    get 'home/profile', to: 'home#profile'
    patch 'home/update_profile', to: 'home#update_profile'

    resources :model_answers
    resources :admissions do
      post :create_installment, on: :collection
    end
    resources :study_pdfs
    resources :notifications
    resources :progress_cards
    resources :messages
    resources :live_classes
  end


  # routes of admin panel
  namespace :admin do
    root to: 'dashboard#show'
    resource :dashboard
    resources :reports do
      get :exam_detailed_report
      get :generate_progress_report
    end
    resources :exams do
      collection do
        get 'question_bank', to: 'exams#question_bank'
        get 'new_jee', to: 'exams#new_jee'
        post 'change_question_answer'
        post :create_section
      end
      get :re_evaluate_exam
    end
    resources :practice_questions
    resources :students do
      root to: 'students#index'
      get   :import, on: :collection
      post  :process_import, on: :collection
      post  :process_import_fees_due, on: :collection
      get   :reset_login
      get   :disable
      get   :enable
      get   :progress_report
      get   :attendance_report
      post  :attendance_report
      post  :attendance_report_pdf
    end
    resources :batches do
      root to: 'batches#index'
      get   :disable
      get   :change_batches, on: :collection
      post  :process_change_batches, on: :collection
      get   :downoload_cet
    end
    resources :batch_groups

    get 'dashboard/profile', to: 'dashboard#profile'
    patch 'dashboard/update_profile', to: 'dashboard#update_profile'

    resources :video_lectures do
      get :chats
      get :student_video_views
      get :modity_student_views
    end
    resources :android_apps
    resources :users do
      get :profile, on: :collection
    end
    resources :study_pdfs
    resources :notifications
    resources :genres do
      get :hide
      get :show
      put :student_folder_access
    end
    resources :study_pdf_types
    resources :messages
    resources :zoom_meetings do
      get :chats
    end
    resources :subjects
    resources :omr
    resources :attendance do
      get :overview_report, on: :collection
      get :settings, on: :collection
      get :sms_logs, on: :collection
      post :change_auto_sms_settings, on: :collection
      post :send_batch_sms, on: :collection
      get :download_xls_report, on: :collection
      collection do
        resources :holidays
      end
    end

    resources :micro_payments
    resources :banners
    resources :att_machines do
      patch :enable
      patch :disable
    end

    resources :id_cards, only: [:index] do
      post :upload_photos, on: :collection
      get :print_cards, on: :collection
      post :print_cards, on: :collection
      post :generate_prints, on: :collection
    end

    namespace :api do
      resources :students
      resources :attendance
      resources :demo_logins

      # new admin api's for admin react front end.
      namespace :v2 do
        get 'get-token', to: 'auth#get_token'
        post 'login', to: 'auth#login'
        get 'fees-details', to: 'fees#details'
        get 'payment-history', to: 'fees#payment_history'
        post 'fees-transaction', to: 'fees#create_fees_transaction'
        get  'reports/collection', to: 'fees_reports#collection'
        get  'reports/collection_csv', to: 'fees_reports#collection_csv'
        get  'reports/due_fees', to: 'fees_reports#due_fees'
        get  'reports/due_fees_csv', to: 'fees_reports#due_fees_csv'
        get  'reports/notes', to: 'fees_reports#notes'
        get  'reports/print_status', to: 'fees_reports#print_status'
        post 'reports/set_print_status', to: 'fees_reports#set_print_status'
        get  'reports/pending-fees', to: 'fees_reports#pending_fees'
        get  'batches', to: 'batches#index'
        resources :students do
          get   :pending_amount, on: :collection
          get   :issued_notes
          post  :issue_notes
          post  :apply_discount
          get   :suggested_roll_number, on: :collection
          post  :change_course

          collection do
            resources :discounts, only: [:index, :create] do
              post :remove_discount, on: :collection
            end
          end
        end
        resources :notes
      end
    end
  end

  get 'current-server-time', to: 'home#current_server_time'

  namespace :api do
    namespace :v1 do
      post 'sign-in', to: 'students#login'
      post 'update-fcm-token', to: 'students#update_fcm_token'
      get  'is-form-registered', to: 'students#is_form_registered'
      get 'dashboard_data', to: 'home#dashboard_data'
      get 'gallery', to: 'home#gallery'
      get 'app-version', to: 'home#app_version'
      get 'categories', to: 'videos#categories'
      get 'categories/:id/videos', to: 'videos#category_videos'

      resources :notifications, only: [:index]
      resources :videos, only: [:index] do
        get   :get_yt_url
        post  :set_yt_url
        get   :need_url
        get   :get_ytdlp_url
        get   :get_ytdlp_url_from_youtube
      end
      resources :study_pdfs, only: [:index]
      resources :meetings, only: [:index]
      resources :trackers
    end

    # NEW ROUTES
    namespace :v2 do
      resources :students, only: [:index] do
        post 'login', on: :collection
        get  :progress_report, on: :collection
        post :register, on: :collection
        get  :de_active, on: :collection
      end
      resources :notifications
      resources :exams
      get 'subjects', to: 'subjects#index'
      get 'subjects/:id/folders', to: 'subjects#subject_folders'
      get 'subjects/:subject_id/folders/:folder_id/pdfs', to: 'subjects#folder_pdfs'
      get 'subjects/:subject_id/folders/:folder_id/videos', to: 'subjects#folder_videos'
      resources :videos, only: [] do
        post :like
        post :dislike

        get :comments
        post :add_comment
        post :remove_comment
        get :tp_streams_details
      end
    end
  end
end

app/models/zoom_meeting.rb
# == Schema Information
#
# Table name: zoom_meetings
#
#  id                  :bigint(8)        not null, primary key
#  datetime_of_meeting :datetime
#  live_type           :integer          default("zoom")
#  password            :string
#  subject             :string
#  teacher_name        :string
#  vimeo_live_show_url :string
#  vimeo_live_url      :string
#  zoom_meeting_url    :string
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  org_id              :bigint(8)
#  zoom_meeting_id     :string
#
# Indexes
#
#  index_zoom_meetings_on_org_id  (org_id)
#

class ZoomMeeting < ApplicationRecord
  has_many :batch_zoom_meetings
  has_many :batches, through: :batch_zoom_meetings
  belongs_to :org

  before_save :sanitize_meeting_id

  enum live_type: {zoom: 0, vimeo: 1}

  def to_json
    {
      zoom_meeting_id: zoom_meeting_id,
      password: password,
      teacher: teacher_name,
      subject: subject,
      date: datetime_of_meeting.strftime("%d-%B-%Y"),
      time: datetime_of_meeting.strftime("%r"),
    }
  end

  private

  def sanitize_meeting_id
    self.zoom_meeting_id = zoom_meeting_id.squish.gsub(/\s/, "") if zoom_meeting_id.present?
  end
end

app/controllers/admin/zoom_meetings_controller.rb
class Admin::ZoomMeetingsController < Admin::BaseController
  ITEMS_PER_PAGE = 20
  def index
    @meetings = ZoomMeeting.includes(:org)
    .where(org: current_org)
    .includes(:batches, :batch_zoom_meetings)
    .where(batches: {id: current_admin.batches&.ids})
    .all
    .order(id: :desc)
    .page(params[:page])
    .per(params[:limit] || ITEMS_PER_PAGE)
  end

  def new
    @batches_with_group = Batch.where(org: current_org, id: current_admin.batches&.ids).all_batches.order(:id).group_by(&:batch_group_id)
    @batch_groups = BatchGroup.where(org: current_org).order(:id).index_by(&:id)
  end

  def edit
    @zoom_meeting = ZoomMeeting.find_by(org: current_org, id: params[:id])
    @selected_batch_ids = @zoom_meeting.batches.ids
    @batches_with_group = Batch.where(org: current_org, id: current_admin.batches&.ids).all_batches.order(:id).group_by(&:batch_group_id)
    @batch_groups = BatchGroup.where(org: current_org).order(:id).index_by(&:id)
  end

  def chats
    @live_class = ZoomMeeting.find_by(id: params[:zoom_meeting_id])
    @admin = current_admin
    @messages = Message.where(messageable: @live_class)
  end

  def update
    meeting = ZoomMeeting.find_by(org: current_org, id: params[:id])
    if meeting && validate_meeting_params
      meeting.zoom_meeting_id = params[:zoom_meeting_id]
      meeting.password = params[:password]
      meeting.subject = params[:subject]
      meeting.teacher_name = params[:teacher_name]
      meeting.datetime_of_meeting = params[:datetime_of_meeting]
      meeting.live_type = ZoomMeeting.live_types[params[:live_type].to_s]
      meeting.vimeo_live_url = params[:vimeo_live_url]
      meeting.zoom_meeting_url = params[:zoom_meeting_url]
      if meeting.save
        if params[:batches].present?
          BatchZoomMeeting.where(zoom_meeting_id: meeting.id).destroy_all
          params[:batches].each do |batch_id|
            BatchZoomMeeting.create(batch_id: batch_id, zoom_meeting_id: meeting.id)
          end
        end
        flash[:success] = "Meeting updated, successfully"
      else
        flash[:error] = "Error in updating Meeting.."
      end
    else
      flash[:error] = "No Meeting found."
    end

    redirect_to "#{admin_android_apps_path}#zoom_meetings"
  end

  def create
    meeting = ZoomMeeting.new
    if validate_meeting_params
      meeting.zoom_meeting_id = params[:zoom_meeting_id]
      meeting.password = params[:password]
      meeting.subject = params[:subject]
      meeting.teacher_name = params[:teacher_name]
      meeting.datetime_of_meeting = params[:datetime_of_meeting]
      meeting.org_id = current_org.id
      meeting.live_type = ZoomMeeting.live_types[params[:live_type].to_s]
      meeting.vimeo_live_url = params[:vimeo_live_url]
      meeting.zoom_meeting_url = params[:zoom_meeting_url]
      if meeting.save
        meeting.update({vimeo_live_show_url: "students/live_classes/#{meeting.id}"})
        if params[:batches].present?
          params[:batches].each do |batch_id|
            BatchZoomMeeting.create(batch_id: batch_id, zoom_meeting_id: meeting.id)
          end
        end
        flash[:success] = "Meeting created, successfully"
      else
        flash[:error] = "Error in creating Meeting.."
      end
    end

    redirect_to "#{admin_android_apps_path}#zoom_meetings"
  end

  def destroy
    meeting = ZoomMeeting.find_by(org: current_org, id: params[:id])
    meeting.destroy if meeting.present?
    flash[:success] = "Meeting deleted, successfully"

    redirect_to "#{admin_android_apps_path}#zoom_meetings"
  end

  def validate_meeting_params
    if(params[:live_type] == 'zoom')
      params[:zoom_meeting_id].present? && params[:password].present? && params[:datetime_of_meeting].present?
    else
      params[:vimeo_live_url].present?
    end
  end
end

app/views/admin/zoom_meetings/chats.html.erb
  <div class="col-md-10">
    <h4>live Chat Messages</h4>
    <div class="msg-container">
      <% @messages.each do |message| %>
        <div class="<%= message.sender_type == 'Student' ? 'student-msg' : 'admin-msg' %>">
          <p>
            <b>[<%= message.sender_id%>] <%= message.sender_name%>:</b>
            <%= message.message %>
          </p>
          <span class="time-right">
            <%= message.created_at.strftime("%I:%M %p") %>
          </span>
        </div>
      <% end %>
    </div>

    <div class="input-group">
        <input id="chatMessage" type="text" class="form-control border-0" placeholder="Enter your message..." data-name="<%= @admin.name %>" ">
        <span id="sendMessage" class="input-group-addon btn btn-primary" style="width: 75px;">
            Send
        </span>
    </div>
  </div>


<script>
  function setupActionCable() {
    App.video_chat = App.cable.subscriptions.create({channel: 'VideoChatChannel', id: "<%= @live_class.id %>"}, {
      connected: function () {
        console.log("AC:: ACTION CABLE ==> Connected");
      },
      disconnected: function () {
        console.log("AC:: ACTION CABLE dis-connected");
      },
      received: function (data) {
        console.log("AC:: DATA => ", data);
        $(".msg-container").append(data.message);
        $(".msg-container").animate({ scrollTop: $('.msg-container').prop("scrollHeight")}, 1000);
      }
    });
  };

  $(document).ready(function(){
    // setupActionCable();

    $("#sendMessage").click(function(){
      var msg = $("#chatMessage").val();
      var name = $("#chatMessage").data("name");
      $("#chatMessage").val('');

      var formData = {
        message: msg,
        sender_name: "<%= @admin.name %>",
        sender_type: 'Admin',
        sender_id: "<%= @admin.id %>",
        messageable_type: "<%= @live_class&.class&.name %>",
        messageable_id: "<%= @live_class&.id %>",
      };

      $.ajax({
        url : "/admin/messages",
        type: "POST",
        data : formData,
        success: function(data, textStatus, jqXHR) {
          console.log("SUCCESS", data);
        },
        error: function (jqXHR, textStatus, errorThrown) {
          console.log("ERROR", errorThrown);
        }
      });

    });
  });
</script>


<style>
.msg-container {
  height: 488px;
  overflow-y: auto;
}
.student-msg {
  background-color: #bfbfbf;
  padding: 10px 5px 25px 5px;
  border-radius: 5px;
  margin: 10px 0px;
}
.admin-msg {
  background-color: #99cdf9;
  padding: 10px 5px 25px 5px;
  border-radius: 5px;
  margin: 10px 0px;
}
.time-right {
  float: right;
  color: #000;
}

.time-left {
  float: left;
  color: #000;
}
</style>;

app/views/admin/zoom_meetings/edit.html.erb
<div class="row" >
  <div class="col-lg-8" style="background-color:rgb(222, 222, 222); ">
    <%= form_tag(admin_zoom_meeting_path(@zoom_meeting), method: :PUT) do %>
      <div class="card-body">
        <h3 class="card-title">Edit Zoom Meeting</h3>

        <div class="pull-right">
          <label class="selectgroup-item">
            <input type="radio" name="live_type" value="zoom" class="selectgroup-input"  <%= @zoom_meeting.zoom? ? 'checked' : '' %>>
            <span class="selectgroup-button">Zoom Live</span>
          </label>
          <label class="selectgroup-item">
            <input type="radio" name="live_type" value="vimeo" class="selectgroup-input"  <%= @zoom_meeting.vimeo? ? 'checked' : '' %> >
            <span class="selectgroup-button">Vimeo Live</span>
          </label>
        </div>
        <div id="zoom-container">
          <div class="form-group">
            <input type="text" value="<%= @zoom_meeting.zoom_meeting_id %>" class="form-control" name="zoom_meeting_id" id="zoom_meeting_id" placeholder="Enter Zoom Meeting Id" required>
          </div>

          <div class="form-group">
            <input type="text" value="<%= @zoom_meeting.password %>" class="form-control" name="password" id="password" placeholder="Enter Zoom Meeting Password" required>
          </div>

          <div class="form-group">
            <input type="text" value="<%= @zoom_meeting.zoom_meeting_url %>"  class="form-control" name="zoom_meeting_url" id="zoom_meeting_url" placeholder="Enter Zoom Meeting URL">
            <span style="font-size: 10px">This URL is only required for web access to zoom meetings</span>
          </div>
        </div>

        <div id="vimeo-container">
          <div class="form-group">
            <input type="text" value="<%= @zoom_meeting.vimeo_live_url %>" class="form-control" name="vimeo_live_url" id="vimeo_live_url" placeholder="Enter Vimeo Live URL">
          </div>
        </div>

        <div class="form-group">
          <input type="text" value="<%= @zoom_meeting.subject %>" class="form-control" name="subject" id="teacher_name" placeholder="Enter subject" required>
        </div>

        <div class="form-group">
          <input type="text" value="<%= @zoom_meeting.teacher_name %>" class="form-control" name="teacher_name" id="teacher_name" placeholder="Enter teacher name" required>
        </div>

        <div class="form-group">
          <p>Time Of Meeting</p>
          <input type="datetime-local" value="<%= @zoom_meeting.datetime_of_meeting.strftime('%Y-%m-%dT%R') %>" name="datetime_of_meeting" id="datetime_of_meeting" placeholder="Time of meeting" required>
        </div>

        <%= render partial: 'admin/select_batches', locals: {var_name: 'batches[]', selected_batches: @selected_batch_ids } %>

        <input type="submit" class="btn btn-primary pull-right" />
        <br>
      </div>

    <% end %>
  </div>
</div>

<script>
  $(document).ready(() => {

    <% if @zoom_meeting.zoom? %>
      $('#vimeo-container').hide();
    <% else %>
      $('#zoom-container').hide();
    <% end %>

    $("input[type='radio']").click(function() {
      if(this.value === 'vimeo') {
        $('#zoom-container').hide();
        $('#vimeo-container').show();
      } else {
        $('#zoom-container').show();
        $('#vimeo-container').hide();
      }
    });
  });
</script>

app/views/admin/zoom_meetings/index.html.erb
<div class="row" style="margin-left: -25px">
  <div class="col-12">
    <div class="card">
      <div class="card-header">
        <div class="col-md-2">
          <h5 class="pt-3">Zoom Meetings</h5>
        </div>
        <div class="offset-md-8 col-xl-2 col-lg-2 col-md-2 col-sm-3 col-2 text-right">
          <%= link_to 'Add New Meeting', new_admin_zoom_meeting_path, method: :get, class: "btn btn-warning btn-sm" %>
        </div>
      </div>
      <div class="card-body">
        <div class="table-responsive">
          <% if @meetings.present? %>
            <table class="table card-table table-striped tabler-hover table-vcenter text-nowrap">
              <thead>
                <tr>
                  <th>Id</th>
                  <th>Meeting Id</th>
                  <th>Password.</th>
                  <th>Subject.</th>
                  <th>Teacher.</th>
                  <th>Date & Time</th>
                  <th>Batch(s)</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                <% @meetings.each do |meeting| %>
                  <tr>
                    <td><%= meeting.id %></td>
                    <td><%= meeting.zoom_meeting_id %></td>
                    <td><%= meeting.password %></td>
                    <td><%= meeting.subject %></td>
                    <td><%= meeting.teacher_name %></td>
                    <td><%= meeting.datetime_of_meeting&.strftime("%d-%b-%y %r") %></td>
                    <td><%= meeting.batches.pluck(:name).join(', ') %></td>
                    <td>
                      <%= link_to 'Edit', edit_admin_zoom_meeting_path(meeting), method: :get, class: "btn btn-warning btn-sm" %>
                      <%= link_to 'Del', admin_zoom_meeting_path(meeting), method: :delete, class: "btn btn-danger btn-sm" %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
            <%= paginate @meetings %>
          <% else %>
            <div class="alert alert-info">No Meetings's were found.</div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/zoom_meetings/new.html.erb
<div class="row" >
  <div class="col-lg-8" style="background-color:rgb(222, 222, 222); ">
    <%= form_tag(admin_zoom_meetings_path, method: :post) do %>
      <div class="card-body">
        <h3 class="card-title">Add New Zoom Meeting</h3>
        <div class="pull-right">
          <label class="selectgroup-item">
            <input type="radio" name="live_type" value="zoom" class="selectgroup-input" required checked>
            <span class="selectgroup-button">Zoom Live</span>
          </label>
          <label class="selectgroup-item">
            <input type="radio" name="live_type" value="vimeo" class="selectgroup-input" required>
            <span class="selectgroup-button">Vimeo Live</span>
          </label>
        </div>
        <div id="zoom-container">
          <div class="form-group">
            <input type="text" class="form-control" name="zoom_meeting_id" id="zoom_meeting_id" placeholder="Enter Zoom Meeting Id">
          </div>

          <div class="form-group">
            <input type="text" class="form-control" name="password" id="password" placeholder="Enter Zoom Meeting Password">
          </div>

          <div class="form-group">
            <input type="text" class="form-control" name="zoom_meeting_url" id="zoom_meeting_url" placeholder="Enter Zoom Meeting URL">
            <span style="font-size: 10px">This URL is only required for web access to zoom meetings</span>
          </div>
        </div>

        <div id="vimeo-container">
          <div class="form-group">
            <input type="text" class="form-control" name="vimeo_live_url" id="vimeo_live_url" placeholder="Enter Vimeo Live URL">
          </div>
        </div>

        <div class="form-group">
          <input type="text" class="form-control" name="subject" id="teacher_name" placeholder="Enter subject" required>
        </div>

        <div class="form-group">
          <input type="text" class="form-control" name="teacher_name" id="teacher_name" placeholder="Enter teacher name" required>
        </div>

        <div class="form-group">
          <p>Time Of Meeting</p>
          <input type="datetime-local" name="datetime_of_meeting" id="datetime_of_meeting" placeholder="Time of meeting" required>
        </div>

        <%= render partial: 'admin/select_batches', locals: {var_name: 'batches[]', selected_batches: [] } %>

        <input type="submit" class="btn btn-primary pull-right" />
        <br>
      </div>

    <% end %>
  </div>
</div>
<script>
  $(document).ready(() => {
    $('#vimeo-container').hide();

    $("input[type='radio']").click(function() {
      if(this.value === 'vimeo') {
        $('#zoom-container').hide();
        $('#vimeo-container').show();
      } else {
        $('#zoom-container').show();
        $('#vimeo-container').hide();
      }
    });
  });
</script>